# ينفذ في طور التطوير فقط
version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app/
    ports:
      - "3000:3000"
    # below exiting with code 0 workaround
    stdin_open: true
    tty: true

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app/
    command: ["npm", "run", "test"]

    stdin_open: true
    tty: true
